#pragma once

#include <string>

using std::string;

enum StoryEvent {
    INTRODUCTION,
    LOCATION_ENTERED,
    CHARACTER_FOUND,
    RABBIT_INJURED,
    OBJECT_EXAMINED,
    OBJECT_ALREADY_EXAMINED,
    OBJECT_CLOSED,
    OBJECT_LOCKED,
    ITEM_FOUND,
    ITEM_COLLECTED,
    NOTHING_FOUND,
    LEAVING_PLACE,
    DAMAGE_RECEIVED,
    GAME_CONTINUED,
    MOVEMENT_UNAVAILABLE,
    DRAWER_AREA_ENTERED,
    SHELF_AREA_ENTERED,
    DRAWER_AREA_RETURNED,
    CORRIDOR_RETURNED,
    CAVITIES_ENTERED,
    CAVITIES_EXITED,
    ACTION_COMPLETED,
    ACTION_FAILED,
    ENDING
};

class Story {
public:
    void show(StoryEvent event, string detail = "");
};